const data = [
  {
    cardName: 'Carta muito loca',
    cardDescription: 'Qualquer coisa',
    cardAttr1: '70',
    cardAttr2: '70',
    cardAttr3: '70',
    cardImage: 'https://picsum.photos/id/237/100',
    cardRare: 'muito raro',
    cardTrunfo: true,
  },
  {
    cardName: 'Outra carta',
    cardDescription: 'Default',
    cardAttr1: '7',
    cardAttr2: '7',
    cardAttr3: '7',
    cardImage: 'https://picsum.photos/id/1022/100',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Terceira carta',
    cardDescription: 'Default',
    cardAttr1: '35',
    cardAttr2: '35',
    cardAttr3: '53',
    cardImage: 'https://picsum.photos/id/3/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Quarta carta',
    cardDescription: 'Default',
    cardAttr1: '4',
    cardAttr2: '24',
    cardAttr3: '24',
    cardImage: 'https://picsum.photos/id/4/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Quinta carta',
    cardDescription: 'Default',
    cardAttr1: '15',
    cardAttr2: '25',
    cardAttr3: '35',
    cardImage: 'https://picsum.photos/id/5/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Sexta carta',
    cardDescription: 'Default',
    cardAttr1: '16',
    cardAttr2: '62',
    cardAttr3: '36',
    cardImage: 'https://picsum.photos/id/6/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Sétima carta',
    cardDescription: 'Default',
    cardAttr1: '7',
    cardAttr2: '27',
    cardAttr3: '73',
    cardImage: 'https://picsum.photos/id/7/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Oitava carta',
    cardDescription: 'Default',
    cardAttr1: '8',
    cardAttr2: '28',
    cardAttr3: '38',
    cardImage: 'https://picsum.photos/id/8/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Nona carta',
    cardDescription: 'Default',
    cardAttr1: '9',
    cardAttr2: '29',
    cardAttr3: '39',
    cardImage: 'https://picsum.photos/id/9/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima carta',
    cardDescription: 'Default',
    cardAttr1: '10',
    cardAttr2: '20',
    cardAttr3: '30',
    cardImage: 'https://picsum.photos/id/10/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima primeira carta',
    cardDescription: 'Default',
    cardAttr1: '11',
    cardAttr2: '21',
    cardAttr3: '31',
    cardImage: 'https://picsum.photos/id/11/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima segunda carta',
    cardDescription: 'Default',
    cardAttr1: '12',
    cardAttr2: '22',
    cardAttr3: '32',
    cardImage: 'https://picsum.photos/id/12/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima terceira carta',
    cardDescription: 'Default',
    cardAttr1: '13',
    cardAttr2: '23',
    cardAttr3: '13',
    cardImage: 'https://picsum.photos/id/13/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima quarta carta',
    cardDescription: 'Default',
    cardAttr1: '14',
    cardAttr2: '24',
    cardAttr3: '34',
    cardImage: 'https://picsum.photos/id/14/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima quinta carta',
    cardDescription: 'Default',
    cardAttr1: '15',
    cardAttr2: '25',
    cardAttr3: '35',
    cardImage: 'https://picsum.photos/id/15/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima sexta carta',
    cardDescription: 'Default',
    cardAttr1: '61',
    cardAttr2: '62',
    cardAttr3: '36',
    cardImage: 'https://picsum.photos/id/16/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima sétima carta',
    cardDescription: 'Default',
    cardAttr1: '17',
    cardAttr2: '27',
    cardAttr3: '37',
    cardImage: 'https://picsum.photos/id/17/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima oitava carta',
    cardDescription: 'Default',
    cardAttr1: '18',
    cardAttr2: '28',
    cardAttr3: '38',
    cardImage: 'https://picsum.photos/id/18/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Décima nona carta',
    cardDescription: 'Default',
    cardAttr1: '19',
    cardAttr2: '29',
    cardAttr3: '39',
    cardImage: 'https://picsum.photos/id/19/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima carta',
    cardDescription: 'Default',
    cardAttr1: '1',
    cardAttr2: '2',
    cardAttr3: '3',
    cardImage: 'https://picsum.photos/id/20/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima primeira carta',
    cardDescription: 'Default',
    cardAttr1: '81',
    cardAttr2: '21',
    cardAttr3: '31',
    cardImage: 'https://picsum.photos/id/21/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima segunda carta',
    cardDescription: 'Default',
    cardAttr1: '12',
    cardAttr2: '22',
    cardAttr3: '23',
    cardImage: 'https://picsum.photos/id/22/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima terceira carta',
    cardDescription: 'Default',
    cardAttr1: '13',
    cardAttr2: '32',
    cardAttr3: '33',
    cardImage: 'https://picsum.photos/id/23/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima quarta carta',
    cardDescription: 'Default',
    cardAttr1: '14',
    cardAttr2: '24',
    cardAttr3: '34',
    cardImage: 'https://picsum.photos/id/24/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima quinta carta',
    cardDescription: 'Default',
    cardAttr1: '15',
    cardAttr2: '25',
    cardAttr3: '35',
    cardImage: 'https://picsum.photos/id/25/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima sexta carta',
    cardDescription: 'Default',
    cardAttr1: '26',
    cardAttr2: '25',
    cardAttr3: '23',
    cardImage: 'https://picsum.photos/id/26/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima sétima carta',
    cardDescription: 'Default',
    cardAttr1: '12',
    cardAttr2: '27',
    cardAttr3: '37',
    cardImage: 'https://picsum.photos/id/27/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima oitava carta',
    cardDescription: 'Default',
    cardAttr1: '28',
    cardAttr2: '28',
    cardAttr3: '38',
    cardImage: 'https://picsum.photos/id/28/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vigésima nona carta',
    cardDescription: 'Default',
    cardAttr1: '4',
    cardAttr2: '67',
    cardAttr3: '32',
    cardImage: 'https://picsum.photos/id/29/100',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Trigésima carta',
    cardDescription: 'Default',
    cardAttr1: '43',
    cardAttr2: '22',
    cardAttr3: '35',
    cardImage: 'https://picsum.photos/id/30/100',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Trigésima primeira carta',
    cardDescription: 'Default',
    cardAttr1: '15',
    cardAttr2: '23',
    cardAttr3: '32',
    cardImage: 'https://picsum.photos/id/31/100',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Trigésima Segunda carta',
    cardDescription: 'Default',
    cardAttr1: '10',
    cardAttr2: '20',
    cardAttr3: '30',
    cardImage: 'https://picsum.photos/id/32/100',
    cardRare: 'normal',
    cardTrunfo: false,
  },
];

export default data;
